spring:
  application:
    name: omin
  datasource:
    #host: localhost, 포트: 5432, DB명: omindb
    url: jdbc:postgresql://localhost:5432/omindb
    username: omin_user
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경 시 DB 테이블 자동 갱신
    show-sql: true     # 실행되는 SQL을 로그로 출력
    properties:
      hibernate:
        format_sql: true
app:
  seed:
    enabled: true  # TODO(prod): 운영에서는 반드시 false 또는 local 프로필로 제한할 것
kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}